### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by KickW** [aydindemircioglu/cuSVMWrapper#1]
Sorry to bother you,  I'd like to ask this cuSVMPredict.cpp . What part of your code is missing? Where do I start?

**Comment by aydindemircioglu** [comment]
hi, i am sorry to say that i have zero clues about the project anymore-- its over 7 years ago.
however, maybe this repo is better suited to your goals?
https://github.com/OrcusCZ/SVMbenchmark

**Comment by KickW** [comment]
> hi, i am sorry to say that i have zero clues about the project anymore-- its over 7 years ago. however, maybe this repo is better suited to your goals? https://github.com/OrcusCZ/SVMbenchmark

Thank you for the information
